#!/usr/bin/env bash
set -e

# TUI apps install script — generated by your config

# apt packages
sudo apt update
sudo apt install -y \
  btop \
  lazygit \
  neovim \
  lynx \
  ncdu \
  cava \
  neomutt \
  aerc \
  glow \
  k9s \
  tig \
  newsboat \
  w3m \
  zoxide \
  tmux \
  taskwarrior \
  calcurse \
  musikcube

# pip packages
pip install --user \
  toot \
  posting \
  harlequin \
  visidata \
  tldr \
  ranger \
  mps-youtube

# cargo (rust) packages — installs rustup if needed
if ! command -v cargo &> /dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source "$HOME/.cargo/env"
fi
cargo install \
  bluetui \
  impala \
  wiremix \
  yazi \
  gitui \
  navi \
  broot \
  zellij \
  trippy \
  bandwhich \
  spotify-tui

# go packages — installs go if needed
if ! command -v go &> /dev/null; then
  sudo apt install -y golang
fi
go install go install github.com/ayn2op/discordo@latest
go install slides
go install lazydocker

# add ~/.local/bin and ~/go/bin to PATH if not already there
grep -qxF 'export PATH="$HOME/.local/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"' ~/.bashrc || \
  echo 'export PATH="$HOME/.local/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

echo "Done! All TUI apps installed."
