#!/bin/bash

echo "start"
echo "Cleaning old builds..."
cargo clean
rm -f Cargo.lock

echo "Building..."
cargo build
echo "done"

if [ -f "nuke.py" ]; then
  echo "File exists."
else
  echo "Creating nuke.py..."
  cat <<'EOF' >nuke.py
import subprocess

ans_gain = False
while not ans_gain:
    ans = input("be host or join?(h/j): ")
    if ans.lower() == "h":
        subprocess.run("cargo run -- host Room_0 7331", shell=True)
        ans_gain = True
    elif ans.lower() == "j":
        subprocess.run("cargo run -- join 127.0.0.1 7331", shell=True)
        ans_gain = True
    else:
        print("Please choose from 'h' or 'j'")
EOF
fi

# Generated by A Fucking Human.
python3 nuke.py
